# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.service.customer_service:
        class: AppBundle\Service\CustomerService
        arguments: ['@doctrine.orm.entity_manager']
    app.service.product_service:
        class: AppBundle\Service\ProductService
        arguments: ['@doctrine.orm.entity_manager']
    app.service.order_service:
        class: AppBundle\Service\OrderService
        arguments: ['@doctrine.orm.entity_manager']
